phoenix_fire_starter/web/router.ex
defmodule FireStarter.Router do
  use FireStarter.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

  end

  # pipeline :authorized do
  #   plug :browser
  #   plug  FireStarter.AuthorizedPlug
  # end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FireStarter do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/events/", EventController, :list
    get "/events/new", EventController, :create
    post "/events/new", EventController, :add
    get "/events/:id", EventController, :show
    get "/login", LoginController, :index
    post "/login", LoginController, :login
    post "/events/:id/reserve", EventController, :reserve
  end

  # scope "events/", FireStarter do
  #   pipe_through :authorized # Use the default authorized stack
  #   get "/", EventController, :list
  #   get "/new", EventController, :create
  #   post "/new", EventController, :add
  #   get "/:id", EventController, :show

  # end


  # Other scopes may use custom stacks.
  # scope "/api", FireStarter do
  #   pipe_through :api
  # end
end

phoenix_fire_starter/lib/events/events.ex
defmodule FireStarter.Events do
  use Ecto.Schema
  import Ecto.Changeset

  schema "events" do
    field :title, :string
    field :description, :string
    field :quantity_available, :integer, default: 25
    timestamps()
  end

  # @required_fields  ~w(title)a
  # @optional_fields  ~w(description)a


  def changeset(event , params \\ %{}) do
    event
    |> cast(params, [:title,:description])
    |> validate_required([:title])
  end

  # def changeset1(event , params \\ %{}) do
  #     event
  #     |> cast(params, @required_fields ++ @optional_fields)
  #     |> validate_required(@required_fields)
  #     #|> validate_change(:date, &must_be_in_future/2)
  # end


  # defp must_be_in_future(_, value) do
  #   Ecto.DateTime.compare(value , Ecto.DateTime.utc)
  #   |>  get_error
  # end

  # defp get_error(comprasion) when comprasion == :lt, do: [date: "Cann't be in past"]
  # defp get_error(_), do: []

end

phoenix_fire_starter/lib/events/events_query.ex
defmodule FireStarter.EventQueries do
  import Ecto.Query

  alias FireStarter.{Repo, Events}

  def any do
    Repo.one(from(e in Events, select: count(e.id))) != 0
  end

  def get_all do
    Repo.all(from(Events))
  end

  def get_data_by_title(title) do
    query =
      from(
        e in Events,
        where: e.title == ^title
      )

    Repo.all(query)
  end

  def get_by_id(id) do
    Repo.get(Events, id)
  end

  def create(event) do
    Repo.insert(event)
  end

  def decrease_quantity(id , quantity) do
    event = Repo.get!(Events, id)
    changes = Ecto.Changeset.change event, quantity_available:
    event.quantity_available - String.to_integer(quantity)
    Repo.update changes
  end


end

phoenix_fire_starter/lib/fire_starter/endpoint.ex
defmodule FireStarter.Endpoint do
  use Phoenix.Endpoint, otp_app: :fire_starter

  socket "/socket", FireStarter.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :fire_starter, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_fire_starter_key",
    signing_salt: "POwjxutW"

  plug FireStarter.Router
end

phoenix_fire_starter/lib/fire_starter/repo.ex
defmodule FireStarter.Repo do
  use Ecto.Repo, otp_app: :fire_starter
end

phoenix_fire_starter/lib/plugs/authorized_plug.ex
defmodule FireStarter.AuthorizedPlug do
  import Plug.Conn
  import Phoenix.Controller
  def init(opts) do
    opts
  end

  def call(conn, name) do
    user_name = conn.cookies["user_name"]
    authorize_user(conn, user_name , name)
  end

  def authorize_user(conn, nil, _) do
    conn
    |> redirect(to: "/login")
    |> halt
  end

  def authorize_user(conn, user_name , name) when user_name === name do
    conn
  end

  def authorize_user(conn, _, _), do: authorize_user(conn, nil, nil)


end

phoenix_fire_starter/web/controllers/event_controller.ex
defmodule FireStarter.EventController do
  use FireStarter.Web, :controller

  plug FireStarter.AuthorizedPlug, "create" when action in [:create]


  def show(conn, %{"id"=>id}) do
    event = FireStarter.EventQueries.get_by_id(id)
    |> IO.inspect()
    render conn, "details.html", event: event
  end
  def list(conn, _params) do
    events = FireStarter.EventQueries.get_all
    render conn, "list.html", events: events
  end


  def create(conn, %{errors: errors}) do
     render conn, "create.html", changeset: errors

  end

  def create(conn, _params) do

    changeset = FireStarter.Events.changeset(%FireStarter.Events{}, %{})
    render conn, "create.html", changeset: changeset

  end

  def add(conn, %{"events"=>events}) do
    changeset = FireStarter.Events.changeset(%FireStarter.Events{}, events)
     #|> FireStarter.EventQueries.create

    case FireStarter.EventQueries.create changeset do
      {:ok , %{id: id}} ->  redirect conn, to: event_path(conn, :show, id)
      {:error , reason} -> create conn, %{errors: reason}
    end
 end


 def reserve(conn , %{"id" => id, "reservation" => %{"quantity" => quantity}} ) do
    {:ok , event} = FireStarter.EventQueries.decrease_quantity(id , quantity)
    FireStarter.EventChannel.send_update(event)
    redirect conn, to: event_path(conn, :show, id)
 end


end

phoenix_fire_starter/web/controllers/login_controller.ex
defmodule FireStarter.LoginController do
  use FireStarter.Web, :controller

  def index(conn, _) do
    render conn, "login.html"
  end

  def login(conn , %{"login" => %{"username" => name}}) do

    expration = 60*60*24*7
    conn
    |> Plug.Conn.put_resp_cookie("user_name", name, max_age: expration )
    |> redirect(to: "/")

  end
end

phoenix_fire_starter/web/controllers/page_controller.ex
defmodule FireStarter.PageController do
  use FireStarter.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

phoenix_fire_starter/web/views/error_view.ex
defmodule FireStarter.ErrorView do
  use FireStarter.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

phoenix_fire_starter/web/views/event_view.ex
defmodule FireStarter.EventView do
  use FireStarter.Web, :view

  def format_date(date)  do
    {{y, m, d}, _} = Ecto.DateTime.to_erl(date)
    "#{m}/#{d}/#{y}"
  end



end

phoenix_fire_starter/web/views/layout_view.ex
defmodule FireStarter.LayoutView do
  use FireStarter.Web, :view
end

phoenix_fire_starter/web/views/login_view.ex
defmodule FireStarter.LoginView do
  use FireStarter.Web, :view
end

phoenix_fire_starter/web/views/page_view.ex
defmodule FireStarter.PageView do
  use FireStarter.Web, :view
end

phoenix_fire_starter/web/views/shared_view.ex
defmodule FireStarter.SharedView do
  use FireStarter.Web, :view
end

phoenix_fire_starter/web/templates/event/create.html.eex
<h1>ADD Event</h1>
<%= form_for @changeset, event_path(@conn, :add ), fn f ->  %>
        <div class="form-group">
            <%= label f, :title, "Title" %>
            <%= text_input f, :title, class: "form-control" %>
            <%= error_tag f, :title  %>
        </div>
          <div class="form-group">
            <%= label f, :description, "Description" %>
            <%= textarea f, :description, class: "form-control"  %>
        </div>
        <%= submit "Add" , class: "btn btn-primary pull-right" %>
<% end %>

phoenix_fire_starter/web/templates/event/details.html.eex
<h1><%= @event.title %></h1>
<p><%= @event.description %></p>
<p><%= @event.inserted_at %></p>
<h4>Available Spots: <span class="quantity"><%= @event.quantity_available %></span></h4>
<%= form_for @conn, event_path(@conn, :reserve, @event.id ), [as: :reservation , class: "form-inline"], fn f ->  %>
        <div class="form-group">
            <%= label f, :quantity, "Quantity" %>
            <%= number_input f, :quantity, class: "form-control" , min: 1 %>
         </div>
         <%= submit "Reserve" , class: "btn btn-primary pull-right" %>
<% end %>
<span id="id" data-id="<%= @event.id %>"></span>

phoenix_fire_starter/web/templates/event/list.html.eex
<h1>All Events</h1>
<a href="<%= event_path(@conn , :create) %>" class="btn btn-primary pull-right"> Add Event</a>
 <%= render FireStarter.SharedView, "count.html", list: @events %>
<div class="list-group">
    <%= for e <- @events do %>
       <%= render "summary.html", event: e, conn: @conn %>
    <% end %>
</div>

phoenix_fire_starter/web/templates/event/summary.html.eex
 <%# <a href="events/<%= @event.id %>
  <a href="<%= event_path(@conn , :show , @event.id) %>">
          <h4>  <%= @event.title %></h4>
        </a>
        <div><%= @event.description %></div>
         <div><%=  @event.inserted_at %></div>

phoenix_fire_starter/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello FireStarter!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
         
            <li><a href="/">Home</a></li>
            <li><a href="<%= login_path(@conn , :index) %>">Login</a></li>
            <li><a href="<%= event_path(@conn , :list) %>">Events</a></li>
            <%# <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li> %>
          </ul>
        </nav>
        <%# <span class="logo"></span> %>
        <%= if @conn.cookies["user_name"] do %>
            <span>Hello, <%= @conn.cookies["user_name"] %></span>
          <% end %>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

phoenix_fire_starter/web/templates/login/login.html.eex
<h1>Login</h1>
<%= form_for @conn, login_path(@conn, :login ), [as: :login], fn f ->  %>
        <div class="form-group">
            <%= label f, :username, "Username" %>
            <%= text_input f, :username, class: "form-control" %>
            
        </div>
         
        <%= submit "Login" , class: "btn btn-primary pull-right" %>
<% end %>

phoenix_fire_starter/web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!!!!!!!!!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

phoenix_fire_starter/web/templates/shared/count.html.eex
<h3>Total Events : <%=  Enum.count @list %></h3>